const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.NoSave,
		C3.Plugins.Mouse,
		C3.Plugins.Spritefont2,
		C3.Plugins.progressbar,
		C3.Plugins.Text,
		C3.Behaviors.Rotate,
		C3.Plugins.Audio,
		C3.Behaviors.scrollto,
		C3.Behaviors.Platform,
		C3.Behaviors.EightDir,
		C3.Behaviors.solid,
		C3.Behaviors.Anchor,
		C3.Plugins.TextBox,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Behaviors.Platform.Exps.JumpStrength,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.CompareY
	];
};
self.C3_JsPropNameTable = [
	{NãoSalvar: 0},
	{logo: 0},
	{background: 0},
	{Play: 0},
	{Mouse: 0},
	{FonteDeSprites: 0},
	{Sprite: 0},
	{BarraDeProgresso: 0},
	{Fade: 0},
	{Texto: 0},
	{Girar: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{image: 0},
	{Sprite4: 0},
	{Texto2: 0},
	{Áudio: 0},
	{Sprite5: 0},
	{checkpointX: 0},
	{checkpointY: 0},
	{CentrarEm: 0},
	{Plataforma: 0},
	{"8Direções": 0},
	{Sprite6: 0},
	{Sólido: 0},
	{bloco: 0},
	{Sprite7: 0},
	{JumpOnTheGreenBlockToBounceHigher: 0},
	{Rectangle: 0},
	{background2: 0},
	{Group: 0},
	{alvoY: 0},
	{ativo: 0},
	{Bandeira: 0},
	{Ellipse: 0},
	{Group3: 0},
	{Texto3: 0},
	{bloco_chao: 0},
	{Group2: 0},
	{Rectangle2: 0},
	{TrustTheWayJumpIntoTheVoid: 0},
	{Rectangle3: 0},
	{Rectangle4: 0},
	{Teleporting: 0},
	{portalA: 0},
	{Rectangle5: 0},
	{Group4: 0},
	{Rectangle6: 0},
	{portalB: 0},
	{Rectangle7: 0},
	{Texto4: 0},
	{Âncora: 0},
	{Group6: 0},
	{Rosa: 0},
	{CollectAllThePointsToAdvanceToTheNextStage: 0},
	{Group5: 0},
	{Group7: 0},
	{Group8: 0},
	{Group9: 0},
	{Texto5: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Rosa2: 0},
	{Group10: 0},
	{alvuY: 0},
	{ativu: 0},
	{Sprite10: 0},
	{Group11: 0},
	{Group12: 0},
	{Group13: 0},
	{Sprite11: 0},
	{velocidade: 0},
	{direcao: 0},
	{Sprite12: 0},
	{Bloco2: 0},
	{BolaRosa: 0},
	{checkpoint: 0},
	{WaitForThePlatformAndAvoidThePinkBallsTheyKill: 0},
	{EntradaDeTexto: 0},
	{TextoAgradecimento: 0},
	{PontosColetados: 0},
	{PontosNecessarios: 0},
	{isMuted: 0},
	{PontosColetados2: 0},
	{PontosNecessarios2: 0},
	{isMuted2: 0}
];

self.InstanceType = {
	logo: class extends self.ISpriteInstance {},
	background: class extends self.ISpriteInstance {},
	Play: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	FonteDeSprites: class extends self.ISpriteFontInstance {},
	Sprite: class extends self.ISpriteInstance {},
	BarraDeProgresso: class extends self.IProgressBarInstance {},
	Fade: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	image: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Texto2: class extends self.ITextInstance {},
	Áudio: class extends self.IInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	bloco: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	JumpOnTheGreenBlockToBounceHigher: class extends self.ISpriteInstance {},
	Rectangle: class extends self.ISpriteInstance {},
	background2: class extends self.ISpriteInstance {},
	Group: class extends self.ISpriteInstance {},
	Bandeira: class extends self.ISpriteInstance {},
	Ellipse: class extends self.ISpriteInstance {},
	Group3: class extends self.ISpriteInstance {},
	Texto3: class extends self.ITextInstance {},
	bloco_chao: class extends self.ISpriteInstance {},
	Group2: class extends self.ISpriteInstance {},
	Rectangle2: class extends self.ISpriteInstance {},
	TrustTheWayJumpIntoTheVoid: class extends self.ISpriteInstance {},
	Rectangle3: class extends self.ISpriteInstance {},
	Rectangle4: class extends self.ISpriteInstance {},
	portalA: class extends self.ISpriteInstance {},
	Rectangle5: class extends self.ISpriteInstance {},
	Group4: class extends self.ISpriteInstance {},
	Rectangle6: class extends self.ISpriteInstance {},
	portalB: class extends self.ISpriteInstance {},
	Rectangle7: class extends self.ISpriteInstance {},
	Texto4: class extends self.ITextInstance {},
	Group6: class extends self.ISpriteInstance {},
	Rosa: class extends self.ISpriteInstance {},
	CollectAllThePointsToAdvanceToTheNextStage: class extends self.ISpriteInstance {},
	Group5: class extends self.ISpriteInstance {},
	Group7: class extends self.ISpriteInstance {},
	Group8: class extends self.ISpriteInstance {},
	Group9: class extends self.ISpriteInstance {},
	Texto5: class extends self.ITextInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Rosa2: class extends self.ISpriteInstance {},
	Group10: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Group11: class extends self.ISpriteInstance {},
	Group12: class extends self.ISpriteInstance {},
	Group13: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Bloco2: class extends self.ISpriteInstance {},
	BolaRosa: class extends self.ISpriteInstance {},
	checkpoint: class extends self.ISpriteInstance {},
	WaitForThePlatformAndAvoidThePinkBallsTheyKill: class extends self.ISpriteInstance {},
	EntradaDeTexto: class extends self.ITextInputInstance {},
	TextoAgradecimento: class extends self.ITextInstance {}
}